### PR TITLE
Fixes Points cell undefined & Cleans up Edit Search btn

### LINKED ISSUE #29: Points page throws an error
```
users.js:314 Uncaught (in promise) TypeError: Cannot read property 'cells' of undefined
    at users.js:314
```

### PR DESCRIPTION
**Pull request by AdamHebby**
No more error, yay! Also cleans up probably the longest line of code in the app

Fixes #29

### CODE REVIEW

File: UI/src/js/users.js [hunk 1]
```diff
@@ -332,29 +336,41 @@ function userSearch(user) {
...
-                         </tr>
-                         <tr>
-                            <td data-toggle="tooltip" data-placement="top" title="The amount of points the user has">Points</td>
-                            <td contenteditable="true" id="editUserPoints">${data[0].points}</td>
-                         </tr>
-                         <tr>
-                      </tbody>
-                   </table>
-      `;
-      document.getElementById("userEditSearchButton").setAttribute('onclick', "editUserTable(tempUser, document.getElementById('EditUserRank').innerHTML, document.getElementById('editUserPoints').innerHTML), $('#modalUserEdit').modal('hide'), UserHandle.editUser(tempUser.toLowerCase(), document.getElementById('EditUserRank').innerHTML, document.getElementById('editUserPoints').innerHTML)")
```
Comment (AdamHebby) [inline UI/src/js/users.js:355]: This line was so long and unreadable, I _had_ to fix it
